/**
 * Keep this project's *.pages.dev twin out of the search index.
 *
 * Generated by divilab-content-hub/scripts/gen-pages-middleware.mjs — do not hand-edit the host.
 *
 * A Worker route cannot cover pages.dev (it is Cloudflare's zone, not ours), and _headers/_redirects
 * are path-only, so a noindex in either would hit the custom domain too. Per-project middleware is
 * the only host-aware hook Pages offers.
 *
 *   velora-colorlib.pages.dev  ->  301  velora.colorlib.com
 *   preview deployments        ->  200 + noindex (must stay usable for testing)
 *   velora.colorlib.com  ->  untouched
 */
const CANONICAL_HOST = "velora.colorlib.com";

export async function onRequest(context) {
  const { request, next } = context;
  const url = new URL(request.url);

  if (!url.hostname.endsWith('.pages.dev')) return next();

  // "<project>.pages.dev" is exactly 3 labels; anything longer is a preview deployment, which must
  // keep working for testing and so is noindexed rather than redirected.
  if (url.hostname.split('.').length === 3) {
    url.hostname = CANONICAL_HOST;
    url.protocol = 'https:';
    return Response.redirect(url.toString(), 301);
  }

  const response = await next();
  const headers = new Headers(response.headers);
  headers.set('X-Robots-Tag', 'noindex, nofollow');
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}
